### ISSUE TITLE
2 nodes with inconsistent version	

### ISSUE THREAD

**Issue by xurwxj** [smizy/docker-hbase#1]
got hint on hbase master web console:
2 nodes with inconsistent version	
![image](https://cloud.githubusercontent.com/assets/683421/25208898/315f7c76-25aa-11e7-9c81-bc9a10004885.png)

env:
docker 1.12.4
hmaster on 1 server
3 regionserver node on 3 server

**Comment by smizy** [comment]
@xurwxj show me your docker-compose.yml configuration.

**Comment by xurwxj** [comment]
ok, thks.
i've done through regenerate docker-compose.yml.
